### ISSUE TITLE
check node version and abort if < 8.10.0

### ISSUE THREAD

**Issue by patrickmcelwee** [marklogic-community/grove-cli#3]
```
testing pmcelwee$ nvm use 6.11
Now using node v6.11.0 (npm v5.5.1)
testing pmcelwee$ grove new test-old-node
-bash: grove: command not found
testing pmcelwee$ npm install -g @marklogic-community/grove-cli
/Users/pmcelwee/.nvm/versions/node/v6.11.0/bin/grove -> /Users/pmcelwee/.nvm/versions/node/v6.11.0/lib/node_modules/@marklogic-community/grove-cli/index.js
+ @marklogic-community/grove-cli@1.0.0-rc.1
added 78 packages in 13.266s
testing pmcelwee$ grove new test-old-node
? Please confirm the name of your new project test-old-node
? Do you want to create your Grove project with the React or the Vue UI? React

Generating a Grove Project named "test-old-node" using the Grove React UI, the Grove Node middle-tier, and ml-gradle...
Cloning into 'test-old-node'...
Submodule 'marklogic' (https://project.marklogic.com/repo/scm/~gjosten/grove-ml-gradle.git) registered for path 'marklogic'
Submodule 'server' (https://project.marklogic.com/repo/scm/nacw/grove-node.git) registered for path 'middle-tier'
Submodule 'ui' (https://project.marklogic.com/repo/scm/~pmcelwee/grove-react-ui.git) registered for path 'ui'
Cloning into '/Users/pmcelwee/work/dev/grove/testing/test-old-node/marklogic'...
Cloning into '/Users/pmcelwee/work/dev/grove/testing/test-old-node/middle-tier'...
Cloning into '/Users/pmcelwee/work/dev/grove/testing/test-old-node/ui'...
Initialized a new git repository

2019-05-13T15:08:23.640Z error: util.promisify is not a function
TypeError: util.promisify is not a function
    at read (/Users/pmcelwee/.nvm/versions/node/v6.11.0/lib/node_modules/@marklogic-community/grove-cli/src/managers/config/grove-node.js:52:6)
    at Object.merge (/Users/pmcelwee/.nvm/versions/node/v6.11.0/lib/node_modules/@marklogic-community/grove-cli/src/managers/config/grove-node.js:63:10)
    at identifyTemplate.then.template (/Users/pmcelwee/.nvm/versions/node/v6.11.0/lib/node_modules/@marklogic-community/grove-cli/src/createNew.js:196:52)
    at process._tickCallback (internal/process/next_tick.js:109:7)`
testing pmcelwee$
``

**Comment by patrickmcelwee** [comment]
should happen on all `grove` commands (`new`, `demo`, `config`)
